### ISSUE TITLE
계산 기록 공유 기능 추가

### ISSUE THREAD

**Issue by jin0yoon** [CodersHigh/SwiftCalc#7]

**Comment by fogbar** [comment]
@lingostar List를 ScrollView + LazyVStack으로 변경한 이유는, SwiftUI의 List가 UIKit의 tableView와 같은 원리로 Cell을 재사용하는데, List의 기본제공 swipe 액션이 delete까지 밖에 지원이 되지 않아서 커스텀을 하려다 보니, List를 건드는 것 보다는 ScrollView + LazyVStack 조합을 사용하는 것이 더 용이하기 때문에 변경하게 되었습니다.
